# Generated by Django 6.0.6 on 2026-06-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(default='KaaNuRO Group', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('kids', 'Kids')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fabric', models.CharField(max_length=100)),
                ('colors', models.CharField(help_text='Comma-separated colors', max_length=255)),
                ('sizes', models.CharField(help_text='Comma-separated sizes', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clothing/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
