# Generated by Django 6.0.6 on 2026-06-30 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blog_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Retail Price (INR)'),
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image Upload'), ('video', 'Video Upload/Embed Link')], default='image', max_length=10)),
                ('file', models.FileField(help_text='Upload product photo or MP4 video snippet', upload_to='product_gallery/')),
                ('embed_url', models.URLField(blank=True, help_text='Optional YouTube/Vimeo video streaming URL code link', null=True)),
                ('clothing_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_media', to='core.clothingitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_media', to='core.product')),
            ],
        ),
    ]
