# Generated by Django 6.0.6 on 2026-07-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='utr_number',
            field=models.CharField(max_length=50, verbose_name='UPI Reference / UTR Number'),
        ),
    ]
