# Generated by Django 6.0.6 on 2026-07-01 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customerprofile_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Payment Awaiting Verification'), ('confirmed', 'Confirmed'), ('processing', 'Processing & Packing'), ('shipped', 'Dispatched')], default='pending', max_length=15),
        ),
    ]
