# Generated by Django 6.0.6 on 2026-07-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_user_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='default_address',
            field=models.TextField(blank=True, null=True, verbose_name='Default Shipping Address'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='customer_avatars/', verbose_name='Profile Avatar'),
        ),
    ]
