# Generated by Django 6.0.6 on 2026-07-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_create_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False, help_text='Feature on homepage Best Sellers shelf', verbose_name='Best Seller'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False, help_text='Feature on homepage New Arrivals shelf', verbose_name='New Arrival'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False, help_text='Feature on homepage Trending shelf', verbose_name='Trending'),
        ),
    ]
