# Generated by Django 6.0.6 on 2026-07-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_blog_featured_image_blog_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Coupon expires at this UTC timestamp. Leave blank for no expiry restriction.', null=True, verbose_name='Valid Until'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Coupon becomes redeemable at this UTC timestamp. Leave blank for no start restriction.', null=True, verbose_name='Valid From'),
        ),
    ]
