# Generated by Django 6.0.6 on 2026-07-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_coupon_validity_window'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmedia',
            name='clothing_item',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Discount value in percentage (0 to 100). Set to 0 for no discount.'),
        ),
        migrations.DeleteModel(
            name='ClothingItem',
        ),
    ]
