# Generated by Django 6.0.6 on 2026-07-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_productmedia_clothing_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('PRIVACY_POLICY', 'Privacy Policy'), ('TERMS_OF_SERVICE', 'Terms of Service')], help_text='The classification archetype of the legal document.', max_length=20, unique=True)),
                ('title', models.CharField(help_text='The public-facing display title for this document entry.', max_length=200)),
                ('content', models.TextField(help_text='The markdown or HTML formatted string content holding the official legal clauses.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
